version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: lift-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - lift_db_data:/var/lib/postgresql/data

volumes:
  lift_db_data:
